// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQZSB6R_lOuNKM07ceH8JJD9zDmcDHMI',
    appId: '1:324311223019:web:b3f5921233f7d2dc014cae',
    messagingSenderId: '324311223019',
    projectId: 'iti-summer-training-5fb06',
    authDomain: 'iti-summer-training-5fb06.firebaseapp.com',
    storageBucket: 'iti-summer-training-5fb06.appspot.com',
    measurementId: 'G-T565J5W31K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGs7LYjAbFzAM69McFDWMrJFp2bOd7Igk',
    appId: '1:324311223019:android:397e562316dcf53e014cae',
    messagingSenderId: '324311223019',
    projectId: 'iti-summer-training-5fb06',
    storageBucket: 'iti-summer-training-5fb06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEVC53-XPGhkydPm0A348aX4yqAD8UCbk',
    appId: '1:324311223019:ios:e388ce8c44a08135014cae',
    messagingSenderId: '324311223019',
    projectId: 'iti-summer-training-5fb06',
    storageBucket: 'iti-summer-training-5fb06.appspot.com',
    iosClientId: '324311223019-or7vlaedq1il83ng6qkvikku9q1al0d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
